---
locale: es
tags:
- pdep
- guia1
- basico
- aritmetica
- aplicacionParcial
layout: input_bottom
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: esNumeroPositivo
